<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "unix_user".
 *
 * @property integer $id
 * @property integer $client_id
 * @property string $db_user
 * @property string $db_pass
 * @property string $db_host
 * @property string $name
 * @property string $home_path
 */
class UnixUser extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'unix_user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['client_id'], 'integer'],
            [['db_user', 'db_pass', 'db_host', 'name', 'home_path'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'client_id' => 'Client ID',
            'db_user' => 'Db User',
            'db_pass' => 'Db Pass',
            'db_host' => 'Db Host',
            'name' => 'Name',
            'home_path' => 'Home Path',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        // TODO это должно быть транзакцией и если где то зафейлились, нужно все откатывать
        // создать директорию пользователя с необходимыми подпапками
        // создать пользователя и группу unix
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
